# Generated by Django 4.0.3 on 2022-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('stduentid', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('money', models.FloatField(max_length=100, null=True)),
                ('date', models.TextField(max_length=500, null=True)),
                ('experieddate', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
