# Generated by Django 4.0.3 on 2022-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_info', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('studentid', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('hallname', models.CharField(max_length=100, null=True)),
                ('roomno', models.TextField(max_length=500, null=True)),
                ('floorno', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
